version: "3.5"

services:
  db:
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calcDB
    image: postgres:16.2-alpine3.19
    ports:
      - "5433:5432"